https_port 1488 cert=/etc/squid/cert.pem key=/etc/squid/key.pem

auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/.htpasswd
auth_param basic realm "Proxy"
acl authenticated proxy_auth REQUIRED
http_access allow authenticated

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access allow authenticated
http_access allow SSL_ports

http_access deny all