# Generated by Django 5.1.4 on 2025-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'olympiads',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='olympiads',
            field=models.ManyToManyField(blank=True, related_name='users', to='olympiads.olympiad'),
        ),
    ]
