# Generated by Django 5.1.2 on 2025-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_olympiad_user_olympiads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='olympiads',
        ),
        migrations.AddField(
            model_name='user',
            name='olympiads',
            field=models.JSONField(default=list),
        ),
    ]
