# Generated by Django 5.1.2 on 2025-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_remove_user_olympiads_user_olympiads'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
